### ISSUE TITLE
Bars do not move on update

### ISSUE THREAD

**Issue by phiaseitz** [ManickYoj/DataVisualization-Project3#16]
Sometimes when selecting a different country, not all of the bars move in the single country visualization

**Comment by ManickYoj** [comment]
Hmm, is this when all countries are deselected? I know about that one, and, if I knew how to clear the graph, I could take care of it. But I didn't know other failure modes exist: any specific cases?

**Comment by phiaseitz** [comment]
I've got it! There's a pull request that resolves this. The reason it happens is that we didn't set counts by segment equal to zero. For the country demographics, there's actually a chance that no respondents from a given country said that the selected country is the most/least. If that's the case, we originally didn't return that count, and the data did not get appended.

**Comment by phiaseitz** [comment]
You're right, though, when no country is selected, we should also not display any data. I can work on that! I think what we'll want to do is just to call the setup single visualization function again.
