### ISSUE TITLE
Single country data representation

### ISSUE THREAD

**Issue by phiaseitz** [ManickYoj/DataVisualization-Project3#7]
We want to represent the data for any given country in a chart. This chart should have the data split up by some demographic categories that are to-be-determined

**Comment by ManickYoj** [comment]
Currently, the country should be saved in GLOBAL.selected.properties.country. It no longer highlights properly, but I'll fix those aspects. It will be updated each time a new country is selected.

**Comment by ManickYoj** [comment]
Disregard last comment - this changes in PR #12 . GLOBAL.selected is now a list of country names EG ["Germany", "France"].

The tabulateData function might be a good hook to update the chart data, as it is updated whenever a new event occurs, and has the already filtered data available.
